# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :release do
    ensure_git_status_clean
    increment_build_number
    build_app(
      scheme: "Weather",
      clean: true,
      configuration: "Release"
    )
    upload_to_app_store(
      force: true,
      overwrite_screenshots: true,
      submit_for_review: true,
      reject_if_possible: true,
      automatic_release: true
    )
    git_commit(path: "*", message: "New release with Fastlane 🚀")
  end
end
